version: "3.3"
services:
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'