
name: backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
defaults:
  run:
    working-directory: backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2.1.0
        with:
          path: |
            ~/.package-lock.json
            **/node_modules
          key: sample_serverless_project_backend_${{ hashFiles('**/.package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        run: npm run deploy dev
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          SUBNET_IDS: ${{ secrets.SUBNET_IDS }}
          SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}