
name: migrations

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Invoke migrations Lambda
        id: migrations
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: enventario-dev-migrate
          LogType: Tail
          InvocationType: RequestResponse

      - name: Display migration logs
        run: echo "${{ fromJSON(steps.migrations.outputs.response).LogResult }}"